import "@fortawesome/free-brands-svg-icons"
import"@fortawesome/free-solid-svg-icons"
import "@fortawesome/react-fontawesome"
import '@fortawesome/fontawesome-svg-core/styles.css'; 
import 'bootstrap/dist/css/bootstrap.min.css';
import { config } from '@fortawesome/fontawesome-svg-core';

config.autoAddCss = false; 

import { Roboto } from 'next/font/google';
import "./globals.css";


const roboto = Roboto({
  weight: ['400', '700'], 
  subsets: ['latin'], 
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
